### ISSUE TITLE
[Bug]: Use new icon style in main menu

### ISSUE THREAD

**Issue by brusch** [pimcore/object-merger#32] opened 2023-03-28 11:58 UTC
### Expected behavior

New monochrome style should be used

### Actual behavior

Old colored icon is still used

### Steps to reproduce

![image](https://user-images.githubusercontent.com/142037/228228986-e8250082-9ecd-4856-9769-c90530fd431a.png)

**Comment by dvesh3** [comment] 2023-03-28 13:11
duplicate of  #28

**Closed as completed by dvesh3** 2023-03-28 13:11 UTC
Labels: Bug
